### ISSUE TITLE
bug: socket hang up

### ISSUE THREAD

**Issue by rajeevchaturvedi2007** [anil614sagar/openapi2apigee#28]
When I am trying to run command -generateApi, it will through error -socket hang up.
Is any one have any idea?

**Comment by anil614sagar** [comment]
Are you using windows OS ?

**Comment by anil614sagar** [comment]
It might be network / proxy / firewall issue.

**Comment by seantdg** [comment]
Hi @anil614sagar ,

I can reproduce this issue on the office network. 

`{
  "code": "ECONNRESET",
  "name": "Error",
  "message": "Error downloading file \"http://petstore.swagger.io/v2/swagger.json\"
socket hang up",
  "stack": "Error: Error downloading file \"http://petstore.swagger.io/v2/swagger.json\"
socket hang up
    at ono (/usr/local/lib/node_modules/openapi2apigee/node_modules/swagger-parser/node_modules/ono/lib/index.js:67:20)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/openapi2apigee/node_modules/swagger-parser/node_modules/json-schema-ref-parser/lib/read.js:195:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketCloseListener (http.js:1522:9)
    at Socket.emit (events.js:117:20)
    at TCP.close (net.js:465:12)

Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.emit (events.js:117:20)
    at TCP.close (net.js:465:12)"
}`

Please could you confirm you are not seeing this error?

**Comment by seantdg** [comment]
Please note - I am able to curl http://petstore.swagger.io/v2/swagger.json successfully

**Comment by rajeevchaturvedi2007** [comment]
This is not network/Proxy issue, others also getting the same error outside my networks.
